server:
  port: 8120 # 服务端口

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 39.102.46.244:8848 # nacos服务器地址
        ip: 8.131.54.86
        port: 8120
    sentinel:
      transport:
        port: 8859 #跟控制台交流的端口，随意指定一个未使用的端口即可
        dashboard: 39.102.46.244:8858 # 指定控制台服务的地址

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    keyid: sddfsdfsdfdfsdf
    keysecret: sddfsdfsdfdfsdf
    #bucket可以在控制台创建，也可以使用java代码创建，注意先测试bucket是否已被占用
    bucketname: bit-jinggong-file